/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.Telas;

import biblioteca.Classes.Livro;
import biblioteca.DAOs.LivroDAO;
import biblioteca.Classes.Periodico;
import biblioteca.DAOs.PeriodicoDAO;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class TelaBalancoAcervo extends javax.swing.JFrame {
    
    
    /**
     * Creates new form BalancoAcervo
     */
    public TelaBalancoAcervo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeriodicos = new javax.swing.JTable();
        jLabelBalancoAcervo1 = new javax.swing.JLabel();
        jLabelPeriodico = new javax.swing.JLabel();
        jLabelLivros2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jLabelQntLivros = new javax.swing.JLabel();
        jTextFieldQntLivros = new javax.swing.JTextField();
        jLabelQntPeriodicos = new javax.swing.JLabel();
        jTextFieldQntTotal = new javax.swing.JTextField();
        jLabelQntTotal = new javax.swing.JLabel();
        jTextFieldQntPeriodicos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTablePeriodicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISSN", "Titulo", "Autor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePeriodicos);
        if (jTablePeriodicos.getColumnModel().getColumnCount() > 0) {
            jTablePeriodicos.getColumnModel().getColumn(0).setResizable(false);
            jTablePeriodicos.getColumnModel().getColumn(1).setResizable(false);
            jTablePeriodicos.getColumnModel().getColumn(2).setResizable(false);
            jTablePeriodicos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabelBalancoAcervo1.setBackground(java.awt.Color.white);
        jLabelBalancoAcervo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBalancoAcervo1.setText("Balanço do Acervo");

        jLabelPeriodico.setBackground(java.awt.Color.white);
        jLabelPeriodico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPeriodico.setText("Periódicos");

        jLabelLivros2.setBackground(java.awt.Color.white);
        jLabelLivros2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLivros2.setText("Livros");

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLivros);
        if (jTableLivros.getColumnModel().getColumnCount() > 0) {
            jTableLivros.getColumnModel().getColumn(0).setResizable(false);
            jTableLivros.getColumnModel().getColumn(1).setResizable(false);
            jTableLivros.getColumnModel().getColumn(2).setResizable(false);
            jTableLivros.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabelQntLivros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQntLivros.setText("Quantidade total de livros no acervo: ");

        jTextFieldQntLivros.setEditable(false);

        jLabelQntPeriodicos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQntPeriodicos.setText("Quantidade total de periódicos no acervo: ");

        jTextFieldQntTotal.setEditable(false);
        jTextFieldQntTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelQntTotal.setBackground(java.awt.Color.white);
        jLabelQntTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQntTotal.setText("Quantidade total de Publicações no acervo:");

        jTextFieldQntPeriodicos.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabelBalancoAcervo1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelQntLivros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldQntLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelQntPeriodicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldQntPeriodicos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabelLivros2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabelQntTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldQntTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabelPeriodico)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBalancoAcervo1)
                .addGap(18, 18, 18)
                .addComponent(jLabelLivros2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQntLivros)
                    .addComponent(jTextFieldQntLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPeriodico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQntPeriodicos)
                    .addComponent(jTextFieldQntPeriodicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQntTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQntTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        exibirPublicacoes();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBalancoAcervo tba = new TelaBalancoAcervo();
                tba.setVisible(true);
                
            }
        });
        
    }
    
    public void exibirPublicacoes(){
        
        LivroDAO ldao = new LivroDAO();
        PeriodicoDAO pdao = new PeriodicoDAO();
        ArrayList<Livro> listaLivro = null;
        ArrayList<Periodico> listaPerio = null;
        
        try{
            listaLivro = ldao.consultar();
            listaPerio = pdao.consultar();
            int qntLivros = 0;
            int qntPerio = 0;
            
            if(!listaLivro.isEmpty()){
                for(int i= 0; i < listaLivro.size(); i++){
                    jTableLivros.setValueAt(listaLivro.get(i).getCodigo(), i, 0);
                    jTableLivros.setValueAt(listaLivro.get(i).getTitulo(), i, 1);
                    jTableLivros.setValueAt(listaLivro.get(i).getAutor(), i, 2);
                    jTableLivros.setValueAt(listaLivro.get(i).getQuantidade_Total(), i, 3);
                    qntLivros += listaLivro.get(i).getQuantidade_Total();
                }
                jTextFieldQntLivros.setText(Integer.toString(qntLivros));
            }else{
                jTextFieldQntLivros.setText("0");
            }
            
            if(!listaPerio.isEmpty()){
                
                for(int i= 0; i < listaLivro.size(); i++){
                    jTablePeriodicos.setValueAt(listaPerio.get(i).getCodigo(), i, 0);
                    jTablePeriodicos.setValueAt(listaPerio.get(i).getTitulo(), i, 1);
                    jTablePeriodicos.setValueAt(listaPerio.get(i).getAutor(), i, 2);
                    jTablePeriodicos.setValueAt(listaPerio.get(i).getQuantidade_Total(), i, 3);
                    qntPerio += listaPerio.get(i).getQuantidade_Total();
                }
                jTextFieldQntPeriodicos.setText(Integer.toString(qntPerio));
            }else{
                jTextFieldQntPeriodicos.setText("0");
            }
            
            jTextFieldQntTotal.setText(Integer.toString(qntLivros + qntPerio));
            
        }catch(SQLException ex){
            System.err.println(ex.getStackTrace().toString());
        }
        
        
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBalancoAcervo1;
    private javax.swing.JLabel jLabelLivros2;
    private javax.swing.JLabel jLabelPeriodico;
    private javax.swing.JLabel jLabelQntLivros;
    private javax.swing.JLabel jLabelQntPeriodicos;
    private javax.swing.JLabel jLabelQntTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTable jTablePeriodicos;
    private javax.swing.JTextField jTextFieldQntLivros;
    private javax.swing.JTextField jTextFieldQntPeriodicos;
    private javax.swing.JTextField jTextFieldQntTotal;
    // End of variables declaration//GEN-END:variables
}
