/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.Telas;

import biblioteca.Classes.Publicacao;
import biblioteca.DAOs.EmprestimoDAO;
import biblioteca.DAOs.LivroDAO;
import biblioteca.DAOs.PeriodicoDAO;
import biblioteca.DAOs.PublicacaoDAO;
import biblioteca.DAOs.UsuarioDAO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class TelaBalancoMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaBalancoMov
     */
    public TelaBalancoMovimentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelBalancoAcervo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTpublicacoes = new javax.swing.JTextField();
        jTextFieldTusuarios = new javax.swing.JTextField();
        jTextFieldTemprestimos = new javax.swing.JTextField();
        jTextFieldMusuario = new javax.swing.JTextField();
        jTextFieldMtempoatraso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePublicacoes = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelBalancoAcervo1.setBackground(java.awt.Color.white);
        jLabelBalancoAcervo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBalancoAcervo1.setText("Balanço de Movimentações");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total de Usuários.......................................................................................:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total de Publicações no acervo................................................................:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total de Empréstimos no mês..................................................................:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Média de Movimentações por Usuário....................................................: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Média de Tempo de Atraso na Devolução das Publicações...................:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("10 Publicações mais Emprestadas");

        jTextFieldTpublicacoes.setEditable(false);
        jTextFieldTpublicacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTpublicacoes.setBorder(null);

        jTextFieldTusuarios.setEditable(false);
        jTextFieldTusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTusuarios.setBorder(null);
        jTextFieldTusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTusuariosActionPerformed(evt);
            }
        });

        jTextFieldTemprestimos.setEditable(false);
        jTextFieldTemprestimos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTemprestimos.setBorder(null);

        jTextFieldMusuario.setEditable(false);
        jTextFieldMusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldMusuario.setBorder(null);

        jTextFieldMtempoatraso.setEditable(false);
        jTextFieldMtempoatraso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldMtempoatraso.setBorder(null);

        jTablePublicacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordem", "Codigo", "Titulo", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePublicacoes);
        if (jTablePublicacoes.getColumnModel().getColumnCount() > 0) {
            jTablePublicacoes.getColumnModel().getColumn(0).setResizable(false);
            jTablePublicacoes.getColumnModel().getColumn(1).setResizable(false);
            jTablePublicacoes.getColumnModel().getColumn(2).setResizable(false);
            jTablePublicacoes.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTpublicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTemprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMtempoatraso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabelBalancoAcervo1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBalancoAcervo1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldTpublicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jTextFieldTemprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldMtempoatraso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTusuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTusuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            jTextFieldTusuarios.setText(Integer.toString(getQuantidadeUsuarios()));
            jTextFieldTpublicacoes.setText(Integer.toString(getQuantidadePublicacoes()));
            jTextFieldTemprestimos.setText(Integer.toString(getQuantidadeEmprestimos()));
            jTextFieldMusuario.setText(Double.toString(getMediaMovimentacaoPorUsuario()));
            jTextFieldMtempoatraso.setText(Integer.toString(getMediaTempoAtraso()) + " dia(s)");
            ArrayList<Publicacao> lista = new ArrayList<Publicacao>();
            EmprestimoDAO edao = new EmprestimoDAO();
            try{
                lista = edao.get10MaisEmprestados();
            }catch(SQLException ex){
                System.err.println(ex);
            }
            
            if(!lista.isEmpty()){
                for(int i= 0; i < lista.size(); i++){
                    jTablePublicacoes.setValueAt((i+1) + "º", i, 0);
                    jTablePublicacoes.setValueAt(lista.get(i).getCodigo(), i, 1);
                    jTablePublicacoes.setValueAt(lista.get(i).getTitulo(), i, 2);
                    jTablePublicacoes.setValueAt(lista.get(i).getAutor(), i, 3);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaBalancoMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
    
    public int getQuantidadeUsuarios() throws SQLException{
        UsuarioDAO udao = new UsuarioDAO();
        return udao.total();
    }
    
    public int getQuantidadePublicacoes() throws SQLException{
        PublicacaoDAO pdao = new LivroDAO();
        return pdao.total();
    }
    
    public int getQuantidadeEmprestimos() throws SQLException{
        EmprestimoDAO edao = new EmprestimoDAO();
        return edao.total();
    }
    
    public double getMediaMovimentacaoPorUsuario() throws SQLException{
        double r = (double) getQuantidadeEmprestimos() / getQuantidadeUsuarios();
        return r;
    }
    
    public int getMediaTempoAtraso() throws SQLException{
        Date d = null;
        EmprestimoDAO edao = new EmprestimoDAO();
        long ms = edao.getAtrasosDevolucoes();
        if(ms != 0){
            d = new Date(ms);
            SimpleDateFormat sdf = new SimpleDateFormat("dd");
            return Integer.parseInt(sdf.format(d));
        }else{
            return 0;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBalancoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBalancoMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBalancoAcervo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePublicacoes;
    private javax.swing.JTextField jTextFieldMtempoatraso;
    private javax.swing.JTextField jTextFieldMusuario;
    private javax.swing.JTextField jTextFieldTemprestimos;
    private javax.swing.JTextField jTextFieldTpublicacoes;
    private javax.swing.JTextField jTextFieldTusuarios;
    // End of variables declaration//GEN-END:variables
}
