/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.Telas;

import biblioteca.Classes.Emprestimo;
import biblioteca.DAOs.EmprestimoDAO;
import biblioteca.DAOs.LivroDAO;
import biblioteca.DAOs.PeriodicoDAO;
import biblioteca.Classes.Publicacao;
import biblioteca.DAOs.PublicacaoDAO;
import biblioteca.Classes.Usuario;
import biblioteca.DAOs.UsuarioDAO;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    Publicacao p = null;
    Usuario u = null;
    
    PublicacaoDAO pdao = null;
    UsuarioDAO udao = new UsuarioDAO();
    EmprestimoDAO edao = new EmprestimoDAO();
    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPublicacaoes = new javax.swing.JLabel();
        grupoTipos = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();
        jRadioButtonLivro = new javax.swing.JRadioButton();
        jLabelCodigo = new javax.swing.JLabel();
        jRadioButtonPeriodico = new javax.swing.JRadioButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelQuantidadeAcervo = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelEmprestimo = new javax.swing.JLabel();
        jLabelQuantidadeDisp = new javax.swing.JLabel();
        jTextFieldQuantidadeDisp = new javax.swing.JTextField();
        jLabelDataDevo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jButtonPesquisarPubl = new javax.swing.JButton();
        jButtonPesquisarUsu = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JFormattedTextField();
        jTextFieldDataEntrega = new javax.swing.JFormattedTextField();

        jLabelPublicacaoes.setBackground(java.awt.Color.white);
        jLabelPublicacaoes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPublicacaoes.setText("Publicações");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimos");

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");

        grupoTipos.add(jRadioButtonLivro);
        jRadioButtonLivro.setText("Livro");
        jRadioButtonLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLivroActionPerformed(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigo.setText("Código:");

        grupoTipos.add(jRadioButtonPeriodico);
        jRadioButtonPeriodico.setText("Periódico");
        jRadioButtonPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPeriodicoActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setText("Título:");

        jLabelAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAutor.setText("Autor:");

        jTextFieldTitulo.setEditable(false);

        jTextFieldAutor.setEditable(false);

        jLabelQuantidadeAcervo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelQuantidadeAcervo.setText("Quantidade:");

        jTextFieldQuantidade.setEditable(false);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jTextFieldMatricula.setToolTipText("Número da Matrícula");

        jTextFieldNome.setEditable(false);
        jTextFieldNome.setToolTipText("Nome Completo");

        jLabelMatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMatricula.setText("Matrícula:");

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Dados do Usuário_______________________________________________");

        jLabelEmprestimo.setBackground(java.awt.Color.white);
        jLabelEmprestimo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEmprestimo.setText("Empréstimo");

        jLabelQuantidadeDisp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelQuantidadeDisp.setText("Disponível:");

        jTextFieldQuantidadeDisp.setEditable(false);

        jLabelDataDevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataDevo.setText("Data de entrega:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelData.setText("Data:");

        jButtonPesquisarPubl.setText("Pesquisar");
        jButtonPesquisarPubl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPublActionPerformed(evt);
            }
        });

        jButtonPesquisarUsu.setText("Pesquisar");
        jButtonPesquisarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarUsuActionPerformed(evt);
            }
        });

        try {
            jTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelQuantidadeAcervo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabelQuantidadeDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldQuantidadeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelMatricula)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(jTextFieldAutor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonPesquisarUsu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonPesquisarPubl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelData)
                            .addComponent(jLabelTipo))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jLabelDataDevo)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPeriodico))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabelEmprestimo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelUsuario)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addGap(50, 50, 50)
                .addComponent(jButtonCancelar)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelEmprestimo)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataDevo)
                    .addComponent(jLabelData)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonPeriodico)
                            .addComponent(jRadioButtonLivro)
                            .addComponent(jLabelTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarPubl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitulo)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelQuantidadeAcervo)
                        .addComponent(jLabelQuantidadeDisp))
                    .addComponent(jTextFieldQuantidadeDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMatricula)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
        p = null;
        u = null;
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(!jTextFieldData.isEditValid()){
            JOptionPane.showMessageDialog(null, "Data do empréstimo inválida!");
            jTextFieldData.grabFocus();
        }else if(!jTextFieldDataEntrega.isEditValid()){
            JOptionPane.showMessageDialog(null, "Data da devolução inválida!");
            jTextFieldDataEntrega.grabFocus();
        }else if(p == null){
            JOptionPane.showMessageDialog(null, "Publicação não selecionada!");
            jTextFieldCodigo.grabFocus();
        }else if(u == null){
            JOptionPane.showMessageDialog(null, "Usuário não selecionado!");
            jTextFieldMatricula.grabFocus();
        }else{
            Emprestimo e = null;
            e = new Emprestimo(u, jTextFieldData.getText(), jTextFieldDataEntrega.getText(), p);
            //e.dataToString(e.getDataDevolucao());
            try {
                if(edao.inserir(e)){
                    try {
                        if(pdao.alterar(p)){
                            JOptionPane.showMessageDialog(null, "Empréstimo realizado com sucesso!");
                            limparCampos();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }catch (SQLException ex) {
                System.err.println(ex);
            };
        }          
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jRadioButtonLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLivroActionPerformed
        jLabelCodigo.setText("ISBN:");
    }//GEN-LAST:event_jRadioButtonLivroActionPerformed

    private void jRadioButtonPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPeriodicoActionPerformed
        jLabelCodigo.setText("ISSN:");
    }//GEN-LAST:event_jRadioButtonPeriodicoActionPerformed

    private void jButtonPesquisarPublActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPublActionPerformed
        if (!TelaPrincipal.validaNumero(jTextFieldCodigo)) {
            JOptionPane.showMessageDialog(null, "Campo " + jLabelCodigo.getText().replace(":", "")
                    + " não pode ser zero, conter letras ou estar em branco!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCodigo.grabFocus();
        } else {
            int codigo = Integer.parseInt(jTextFieldCodigo.getText());

            if (jRadioButtonLivro.isSelected()) {
                pdao = new LivroDAO();
                try {
                    p = pdao.consultar(codigo);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCadastroPublicacao.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (p != null) {
                    if(p.temDisponivel()){
                        jRadioButtonLivro.setSelected(true);
                        jTextFieldCodigo.setText(Integer.toString(p.getCodigo()));
                        jTextFieldTitulo.setText(p.getTitulo());
                        jTextFieldAutor.setText(p.getAutor());
                        jTextFieldQuantidade.setText(Integer.toString(p.getQuantidade_Total()));
                        jTextFieldQuantidadeDisp.setText(Integer.toString(p.getQuantidadeDisponivel())); 
                    }else{
                        JOptionPane.showMessageDialog(null, "Livro sem exemplar disponível para empréstimo.");
                        limparCampos();
                    }
                   
                } else {
                    JOptionPane.showMessageDialog(null, "Livro não encontrado.");
                }
            } else {
                if (jRadioButtonPeriodico.isSelected()) {
                    pdao = new PeriodicoDAO();
                    try {
                        p = pdao.consultar(codigo);
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaCadastroPublicacao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (p != null) {
                        if(p.temDisponivel()){
                            jRadioButtonPeriodico.setSelected(true);
                            jTextFieldCodigo.setText(Integer.toString(p.getCodigo()));
                            jTextFieldTitulo.setText(p.getTitulo());
                            jTextFieldAutor.setText(p.getAutor());
                            jTextFieldQuantidade.setText(Integer.toString(p.getQuantidade_Total()));
                            jTextFieldQuantidadeDisp.setText(Integer.toString(p.getQuantidadeDisponivel()));
                        }else{
                            JOptionPane.showMessageDialog(null, "Periódico sem exemplar disponível para empréstimo.");
                            limparCampos();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Periódico não encontrado.");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Selecione um tipo!");
                }
            }
        }
    }//GEN-LAST:event_jButtonPesquisarPublActionPerformed

    private void jButtonPesquisarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarUsuActionPerformed
        if(!TelaPrincipal.validaNumero(jTextFieldMatricula)){
             JOptionPane.showMessageDialog(null, "Campo " + jLabelMatricula.getText().replace(":", "") + 
                                          " não pode ser zero, conter letras ou estar em branco!" ,"Informação",JOptionPane.INFORMATION_MESSAGE);
            jTextFieldMatricula.grabFocus();
        }else{
            int matricula = Integer.parseInt(jTextFieldMatricula.getText());
            try{
                u = udao.consultar(matricula);
                if(u != null){
                    jTextFieldMatricula.setText(Integer.toString(u.getMatricula()));
                    jTextFieldNome.setText(u.getNome());
                }else{
                    JOptionPane.showMessageDialog(null, "Matrícula inexistente");
                    this.jTextFieldMatricula.setText("");
                    this.jTextFieldNome.setText("");
                }
            }catch(SQLException e){
                 Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_jButtonPesquisarUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }
    
    public void limparCampos(){
        u = null;
        p = null;
        this.jTextFieldData.setText("");
        this.jTextFieldDataEntrega.setText("");
        grupoTipos.clearSelection();
        this.jTextFieldCodigo.setText("");
        this.jTextFieldTitulo.setText("");
        this.jTextFieldAutor.setText("");
        this.jTextFieldQuantidade.setText("");
        this.jTextFieldQuantidadeDisp.setText("");
        this.jTextFieldMatricula.setText("");
        this.jTextFieldNome.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipos;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPesquisarPubl;
    private javax.swing.JButton jButtonPesquisarUsu;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDataDevo;
    private javax.swing.JLabel jLabelEmprestimo;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPublicacaoes;
    private javax.swing.JLabel jLabelQuantidadeAcervo;
    private javax.swing.JLabel jLabelQuantidadeDisp;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JRadioButton jRadioButtonLivro;
    private javax.swing.JRadioButton jRadioButtonPeriodico;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JFormattedTextField jTextFieldData;
    private javax.swing.JFormattedTextField jTextFieldDataEntrega;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldQuantidadeDisp;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
