/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.Telas;

import biblioteca.Classes.Emprestimo;
import biblioteca.DAOs.EmprestimoDAO;
import biblioteca.DAOs.LivroDAO;
import biblioteca.DAOs.PeriodicoDAO;
import biblioteca.Classes.Publicacao;
import biblioteca.DAOs.PublicacaoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabricio
 */
public class TelaDevolucao extends javax.swing.JFrame {
    /**
     * Creates new form TelaDevolucao
     */
    public TelaDevolucao() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipos = new javax.swing.ButtonGroup();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtonPeriodico = new javax.swing.JRadioButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jRadioButtonLivro = new javax.swing.JRadioButton();
        jLabelCodigo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmprestimos = new javax.swing.JTable();
        jLabelDevPorPub1 = new javax.swing.JLabel();
        jButtonDevolver = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        grupoTipos.add(jRadioButtonPeriodico);
        jRadioButtonPeriodico.setText("Periódico");
        jRadioButtonPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPeriodicoActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setText("Título:");

        jLabelAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAutor.setText("Autor:");

        jTextFieldTitulo.setEditable(false);

        jTextFieldAutor.setEditable(false);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");

        grupoTipos.add(jRadioButtonLivro);
        jRadioButtonLivro.setText("Livro");
        jRadioButtonLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLivroActionPerformed(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigo.setText("Código:");

        jTableEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Usuário", "Data do Empréstimo", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEmprestimos);
        if (jTableEmprestimos.getColumnModel().getColumnCount() > 0) {
            jTableEmprestimos.getColumnModel().getColumn(0).setResizable(false);
            jTableEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTableEmprestimos.getColumnModel().getColumn(1).setResizable(false);
            jTableEmprestimos.getColumnModel().getColumn(2).setResizable(false);
            jTableEmprestimos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabelDevPorPub1.setBackground(java.awt.Color.white);
        jLabelDevPorPub1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDevPorPub1.setText("Devolução de Publicações");

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelDevPorPub1)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButtonDevolver)
                        .addGap(87, 87, 87)
                        .addComponent(jButtonLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTipo)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButtonLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPeriodico))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodigo)
                            .addComponent(jLabelAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jButtonPesquisar))
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabelDevPorPub1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitulo))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonPeriodico)
                            .addComponent(jRadioButtonLivro)
                            .addComponent(jLabelTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo))
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDevolver)
                    .addComponent(jButtonLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private ArrayList<Emprestimo> verificaEmprestimosPublicacao(Publicacao p) throws SQLException{
        ArrayList<Emprestimo> lista = null;
        ArrayList<Emprestimo> listaRetorno = new ArrayList<Emprestimo>();
        EmprestimoDAO edao = new EmprestimoDAO();

        
        try {
            lista = edao.consultar(p);
            if (lista != null) {
                for (Emprestimo l : lista) {
                    if (!l.estaDevolvido()) {
                        listaRetorno.add(l);
                    }
                }
                if(listaRetorno.size() > 0){
                   return listaRetorno; 
                }else{
                    return null;
                }
            } else {
                return null;
            }
        } catch (SQLException ex) {
            return null;
        }
        
    }
    
    private void preencheFormulario(int codigo, PublicacaoDAO dao, JRadioButton botaoTipo){
        Publicacao p = null;
        
        try {
            p = dao.consultar(codigo); //resgata o objeto publicacao
        } catch (SQLException ex) {
            Logger.getLogger(TelaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(p != null){ //achou uma publicacao com o codigo
            ArrayList<Emprestimo> lista = null; 
            try {
                lista = verificaEmprestimosPublicacao(p);
                if(lista != null){
                    botaoTipo.setSelected(true);
                    jTextFieldCodigo.setText(Integer.toString(p.getCodigo()));
                    jTextFieldTitulo.setText(p.getTitulo());
                    jTextFieldAutor.setText(p.getAutor());
                    
                    DefaultTableModel df = (DefaultTableModel) jTableEmprestimos.getModel();
                    df.setRowCount(lista.size());
                    
                    for(int i= 0; i < lista.size(); i++){
                        jTableEmprestimos.setValueAt(lista.get(i).getCodigo(), i, 0);
                        jTableEmprestimos.setValueAt(lista.get(i).getUsuario().getNome(), i, 1);
                        jTableEmprestimos.setValueAt(lista.get(i).dataToString(lista.get(i).getDataEmprestimo()), i, 2);
                        jTableEmprestimos.setValueAt("Pendente", i, 3);
                        
                    }

                }else{
                    JOptionPane.showMessageDialog(null, p.getClass().getSimpleName() + " sem empréstimos pendentes");
                    limparCampos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Publicação não encontrada.");
            limparCampos();
        }
    }
    
    private void limparCampos(){
        this.grupoTipos.clearSelection();
        this.jTextFieldCodigo.setText("");
        this.jTextFieldTitulo.setText("");
        this.jTextFieldAutor.setText("");
        
        for(int i= 0; i < jTableEmprestimos.getRowCount(); i++){
            jTableEmprestimos.setValueAt("", i, 0);
            jTableEmprestimos.setValueAt("", i, 1);
            jTableEmprestimos.setValueAt("", i, 2);
            jTableEmprestimos.setValueAt("", i, 3);
            
        }
        jTableEmprestimos.clearSelection();
        DefaultTableModel df = (DefaultTableModel) jTableEmprestimos.getModel();
        df.setRowCount(0);
    }
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if(!TelaPrincipal.validaNumero(jTextFieldCodigo)){
            JOptionPane.showMessageDialog(null, "Campo " + jLabelCodigo.getText().replace(":", "") + 
                                          " não pode ser zero, conter letras ou estar em branco!" ,"Informação",JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCodigo.grabFocus();
        }else{
            int codigo = Integer.parseInt(jTextFieldCodigo.getText());
            Publicacao p = null;
            PublicacaoDAO dao = null;
            
            if((!jRadioButtonLivro.isSelected()) && (!jRadioButtonPeriodico.isSelected())){
                JOptionPane.showMessageDialog(null, "Selecione um tipo!");
            }else{
                if(jRadioButtonLivro.isSelected()){ 
                    dao = new LivroDAO();
                    preencheFormulario(codigo, dao , jRadioButtonLivro);
                }else{
                    dao = new PeriodicoDAO();
                    preencheFormulario(codigo, dao , jRadioButtonPeriodico);
                }
            } 
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jRadioButtonPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPeriodicoActionPerformed
        jLabelCodigo.setText("ISSN:");
    }//GEN-LAST:event_jRadioButtonPeriodicoActionPerformed

    private void jRadioButtonLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLivroActionPerformed
        jLabelCodigo.setText("ISBN:");
    }//GEN-LAST:event_jRadioButtonLivroActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        if(jTableEmprestimos.getSelectedRow() >= 0){
            int linha = jTableEmprestimos.getSelectedRow();
            int codigo = (int) jTableEmprestimos.getValueAt(linha, 0);
            
            if(JOptionPane.showConfirmDialog(null, "Deseja devolver o empréstimo? ","Confirmação",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                EmprestimoDAO edao = new EmprestimoDAO();
                try {
                    if(edao.devolverEmprestimo(codigo)){
                        JOptionPane.showMessageDialog(null, "Empréstimo devolvido com sucesso!");
                        DefaultTableModel df = (DefaultTableModel) jTableEmprestimos.getModel();
                        df.removeRow(linha);
                        jTableEmprestimos.clearSelection();
                        limparCampos();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(TelaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um registro!");
        }
        
        
    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipos;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDevPorPub1;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JRadioButton jRadioButtonLivro;
    private javax.swing.JRadioButton jRadioButtonPeriodico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmprestimos;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
